spring.application.name=appointmentbooking

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/appointment_db
spring.datasource.username=appointment_user
spring.datasource.password=appointment_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
